
title: Temporary Robot Control Documentation
description: Autonomous Guide
remote_theme: just-the-docs/just-the-docs

search_enabled: true
aux_links:
  "GitHub Repository": "https://github.com/PancakeToaster/PancakeToaster.github.io"

plugins:
  - jekyll-remote-theme
